### ISSUE TITLE
OLED DISPLAY

### ISSUE THREAD

**Issue by drlovelove** [witnessmenow/arduino-google-maps-api#1]
how can I display this data on OLED ? Perhaps SSD1306 ?

**Comment by witnessmenow** [comment]
Funnily enough I'm working on a video at the moment where I do just this and I already have the sketch mostly written

https://github.com/witnessmenow/arduino-traffic-notifier

I am using Telegram to reconfigure the settings, but you can just remove the Telegram parts if you dont want it included.

**Comment by drlovelove** [comment]
Very nice, by Telegram you mean it's an Instant Messneger like Whatsapp? I like this google maps API and I wanted to check the route between my office and home. How about add an LED for the notifications? ( RED , GREEN , YELLOW)

**Comment by witnessmenow** [comment]
I'm going to close this out as there is a provided example. Also [see this video where I talk about the project](https://www.youtube.com/watch?v=KjIRUTPcvCQ)

@drlovelove to answer your questions:

Yeah Telegram is very like whatsapp but it lets you bots which are basically programs that can send and receive messages. I have a Telegram library for Arduino which means you can use Telegram to send and receive messages to and from your Arduino. 

I have since added an LED to the above project, it only has Red and Green, but you could use that as an example to add yellow too

Hope this helps!
